# Generated by Django 3.1.7 on 2021-04-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210415_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='chaos', max_length=128),
        ),
    ]
