# Generated by Django 3.1.7 on 2021-04-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210416_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abs',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(default='', max_length=99999),
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='article',
            name='kws',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='article',
            name='security',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='article',
            name='userid',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='article',
            name='username',
            field=models.CharField(default='', max_length=128),
        ),
    ]
