# Generated by Django 3.1.7 on 2021-04-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210416_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('commenter', models.CharField(default='', max_length=128)),
                ('content', models.CharField(default='', max_length=9999)),
                ('date', models.CharField(default='', max_length=32)),
                ('good', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
